[package]
name = "teras-lang-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "TERAS-LANG types"

[dependencies]
teras-lang-lexer.workspace = true
